export const routes = {
  Root: '/',
  Home: '/home',
  Login: '/login',
  Register: '/register',
  Orders: '/orders',
  OrdersBoard: '/board',
  OrderDraft: '/orders/draft',
  OrderDetails: '/orders/detail/:id',
  Customers: '/customers',
  CustomerDraft: '/customers/draft',
  CustomerDetails: '/customers/detail/:id',
  Products : '/products',
  ProductDraft: '/products/draft',
  ProductEdit: '/products/edit/:id',
  ProductDetails: '/products/detail/:id',
  Locations: '/locations',
  LocationDraft: '/locations/draft',
  LocationEdit: '/locations/edit/:id',
  LocationDetails: '/locations/detail/:id',
  Users: '/users',
  UserDraft: '/users/draft',
  UserEdit: '/users/edit/:id',
  UserDetails: '/users/detail/:id',
  Settings: '/settings',
};
