export const routes = {
  Home: '/',
  Login: '/login',
  Register: '/register',
  OrdersBoard: '/board',
  OrderDraft: '/orders/draft',
  OrderDetails: '/orders/detail/:id',
  Customers: '/customers',
  CustomerDraft: '/customers/draft',
  CustomerDetails: '/customers/detail/:id',
  Products : '/products',
  ProductDraft: '/products/draft',
  ProductDetails: '/products/detail/:id',
  Settings: '/settings',
};
