import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import {
  TuiAppearance,
  tuiAppearanceState,
  TuiAutoColorPipe,
  TuiButton,
  TuiDataList,
  TuiDropdown,
  TuiGroup,
  TuiIcon,
  TuiPopup,
  TuiRoot,
  TuiTextfield,
} from '@taiga-ui/core';
import {
  TuiAccordion,
  TuiAvatar,
  TuiBadge,
  TuiBadgeNotification,
  TuiBlock,
  TuiButtonClose,
  TuiCarousel,
  TuiCheckbox,
  TuiChevron,
  TuiChip,
  TuiCopy,
  TuiDataListDropdownManager,
  TuiDrawer,
  TuiFade,
  TuiPagination,
  TuiPassword,
  TuiRadio,
  TuiSegmented,
  TuiSwitch,
} from '@taiga-ui/kit';
import {
  TuiInputModule,
  TuiInputNumberModule,
  TuiInputPhoneModule,
  TuiMultiSelectModule,
  TuiTextareaModule,
  TuiTextfieldControllerModule,
} from '@taiga-ui/legacy';

@NgModule({
  imports: [
    CommonModule,
    ...TuiAccordion,
    ...TuiCarousel,
    ...TuiDataList,
    ...TuiDropdown,
    ...TuiRadio,
    ...TuiTextfield,
    TuiAppearance,
    TuiAutoColorPipe,
    TuiAvatar,
    TuiBadge,
    TuiBadgeNotification,
    TuiBlock,
    TuiButton,
    TuiButtonClose,
    TuiCheckbox,
    TuiChevron,
    TuiChip,
    TuiCopy,
    TuiDataListDropdownManager,
    TuiDrawer,
    TuiFade,
    TuiGroup,
    TuiIcon,
    TuiInputModule,
    TuiInputNumberModule,
    TuiInputPhoneModule,
    TuiMultiSelectModule,
    TuiPagination,
    TuiPassword,
    TuiPopup,
    TuiRoot,
    TuiSegmented,
    TuiSwitch,
    TuiTextareaModule,
    TuiTextfieldControllerModule,
  ],
  exports: [
    TuiRoot,
    ...TuiAccordion,
    ...TuiCarousel,
    ...TuiDataList,
    ...TuiDropdown,
    ...TuiRadio,
    ...TuiTextfield,
    TuiAppearance,
    TuiAutoColorPipe,
    TuiAvatar,
    TuiBadge,
    TuiBadgeNotification,
    TuiBlock,
    TuiButton,
    TuiButtonClose,
    TuiCheckbox,
    TuiChevron,
    TuiChip,
    TuiDataListDropdownManager,
    TuiDrawer,
    TuiFade,
    TuiGroup,
    TuiIcon,
    TuiInputModule,
    TuiInputNumberModule,
    TuiInputPhoneModule,
    TuiMultiSelectModule,
    TuiPagination,
    TuiPassword,
    TuiPopup,
    TuiSegmented,
    TuiSwitch,
    TuiTextareaModule,
    TuiTextfieldControllerModule,
  ],
})
export class TUIModule {}
